## Density Functional Perturbation Theory (DFPT)
---

In this notebook we will move to the perturbation theory calculation of phonon frequencies. This type of calculation is another step up on the scale of computational complexity and demands. Thus, the warnings about *not* following blindly the presented scheme in the real calculations applies here even more. The calculation is modeled after one of the AbInit tutorials.

We will calculate for AsAl:
- Dynamical matrix at $\Gamma$ and X
- Phonon frequencies at $\Gamma$ and X
- Born effective charges
- Dielectric tensor
- LO-TO splitting


### Calculation setup

In [1]:
%pylab inline
import ase
import ase.io
from ase.spacegroup import crystal
from ase.calculators.abinit import Abinit
from ase import units as un
from elastic import get_pressure

# Utility functions
from tqdm.auto import tqdm
import spglib
from abilib import scan_param, set_params

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [2]:
import subprocess
import os
from ase.calculators.calculator import CalculationFailed

def run_calc(cryst):
    '''
    Run the calculation without reading back any results into cryst.
    '''
    cryst.calc.write_inputfiles(cryst, ['energy', 'positions'])
    cryst.calc.template.execute(cryst.calc.directory, cryst.calc.profile)
    # cmd = cryst.calc.command.replace('PREFIX', cryst.calc.prefix)
    # proc = subprocess.Popen(cmd, shell=True, cwd=cryst.calc.directory)
    # errorcode = proc.wait()
    # if errorcode:
    #     path = os.path.abspath(cryst.calc.directory)
    #     msg = ('Calculator "{}" failed with command "{}" failed in '
    #            '{} with error code {}'.format(cryst.calc.name, cmd,
    #                                           path, errorcode))
    #     raise CalculationFailed(msg)
    return True

In [3]:
a = 5.61456927
prim = crystal(('As','Al'), basis=((0,0,0), (1/4,1/4,1/4)), 
        spacegroup=216, cellpar=(a, a, a, 90, 90, 90),
        primitive_cell=True)

prim.cell.cellpar()

array([ 3.9701,  3.9701,  3.9701, 60.    , 60.    , 60.    ])

In [4]:
prim.get_scaled_positions()

array([[0.  , 0.  , 0.  ],
       [0.25, 0.25, 0.25]])

In [5]:
spglib.get_spacegroup((prim.cell, prim.get_scaled_positions(), prim.get_atomic_numbers()))

'F-43m (216)'

In [6]:
lat = prim.cell.get_bravais_lattice()
print(lat.description())

FCC(a=5.61457)
  Variant name: FCC
  Special point names: GKLUWX
  Default path: GXWKGLUWLK,UX

  Special point coordinates:
    G   0.0000  0.0000  0.0000
    K   0.3750  0.3750  0.7500
    L   0.5000  0.5000  0.5000
    U   0.6250  0.2500  0.6250
    W   0.5000  0.2500  0.7500
    X   0.5000  0.0000  0.5000



In [7]:
work_dir = 'work_10'

In [8]:
def create_calculator(directory=work_dir, ecut=420):
    return Abinit(directory=directory,             
              ecut= ecut,
              #pps = 'pspnc', tolvrs=1.0e-18, nband=4,
              pps = 'pawxml', pawecutdg = 750, xc = 'LDA', toldfe = 1.0e-6,
              diemac=9.0,
              nstep=15,
              kptrlatt=[[-4,  4,  4],
                        [ 4, -4,  4],
                        [ 4,  4, -4]]
              )

In [9]:
prim.calc = create_calculator()

In [10]:
print(f'  Energy:  {prim.get_potential_energy():.3f} eV')
print( '  Stress: [', 6*' %6.2f' % tuple(prim.get_stress()/un.GPa), '] GPa')
print(f'Pressure:     {get_pressure(prim.get_stress())/un.GPa:.3f} GPa')

  Energy:  -3164.646 eV
  Stress: [   -0.44  -0.44  -0.44   0.00   0.00   0.00 ] GPa
Pressure:     0.444 GPa


In [11]:
prim.get_forces()

array([[-0., -0.,  0.],
       [ 0., -0., -0.]])

### Convergence scan
---
This is a reminder that you should *always* perform convergence analysis of your calculations. We can skip this step by setting `Scan_Corvengence = False` , since we have already performed this analysis in previous part.

In [12]:
Scan_Corvengence = False

In [13]:
if Scan_Corvengence :
    ecut = prim.calc.parameters['ecut']
    ecuts, eres = scan_param(prim, 'ecut', 200, 500)

    figsize(6,6)
    subplot(211)
    plot(ecuts, eres[0], 'o')
    ylabel('Energy (eV)')
    subplot(212)
    plot(ecuts, eres[1]/un.GPa, 'o')
    ylabel('Pressure (GPa)')
    xlabel('ecut (eV)');
    prim.calc.set(ecut=ecut)

### DFPT calculations
---

In [14]:
cr = ase.Atoms(prim)
cr.calc = set_params(create_calculator(f'{work_dir}/AsAl_3'),
            ndtset=4,

            #Ground state calculation
            kptopt1=1,              # Automatic generation of k points, taking
                                    # into account the symmetry
            tolvrs1=1.0e-18,        # SCF stopping criterion
            
            #Response Function calculation : d/dk
            rfelfd2=2,              # Activate the calculation of the d/dk perturbation
            rfdir2=[1, 0, 0],       # Need to consider the perturbation in the x-direction only
                                    # This is rather specific, due to the high symmetry of the AlAs crystal
                                    # In general, just use rfdir 1 1 1
                                    # In the present version of ABINIT (v4.6), symmetry cannot be used
                                    # to reduce the number of ddk perturbations
            nqpt2=1,
            qpt2=[0.0, 0.0, 0.0],   # This is a calculation at the Gamma point

            getwfk2=-1,             # Uses as input the output wf of the previous dataset

            kptopt2=2,              # Automatic generation of k points,
                                    # using only the time-reversal symmetry to decrease
                                    # the size of the k point set.

            iscf2=-3,               # The d/dk perturbation must be treated 
                                    # in a non-self-consistent way
            tolwfr2=1.0e-22,        # Must use tolwfr for non-self-consistent calculations
                                    # Here, the value of tolwfr is very low.          
            
            #Response Function calculation : electric field perturbation and phonons
            rfphon3=1,              # Activate the calculation of the atomic dispacement perturbations
            rfatpol3=[1, 2],        # All the atoms will be displaced
            rfelfd3=3,              # Activate the calculation of the electric field perturbation
            rfdir3=[1, 1, 1],       # All directions are selected. However, symmetries will be used to decrease
                                    # the number of perturbations, so only the x electric field is needed
                                    # (and this explains why in the second dataset, rfdir was set to 1 0 0).

            nqpt3=1,
            qpt3=[0.0, 0.0, 0.0],   # This is a calculation at the Gamma point

            getwfk3=-2,             # Uses as input wfs the output wfs of the dataset 1
            getddk3=-1,             # Uses as input ddk wfs the output of the dataset 2

            kptopt3=2,              # Automatic generation of k points,
                                    # using only the time-reversal symmetry to decrease
                                    # the size of the k point set.
            tolvrs3=1.0e-8,
            
            #Response Function calculation : phonon at X
              rfphon4 = 1,            # Activate the calculation of the atomic dispacement perturbations
             rfatpol4 = [1,2],           # All the atoms will be displaced
               rfdir4 = [1,1,1],         # Need all directions but ABINIT will use symmetries if possible

                nqpt4 = 1,
                 qpt4 = [0.0,0.5,0.5],   # This is a calculation at the X point

              getwfk4 = 1,            # Uses as input wfs the output wfs of the dataset 1

              kptopt4 = 3,            # Automatic generation of k points,
                                      # no use of symmetries to decrease 
                                      # the size of the k point set.
              tolvrs4 = 1.0e-8,

           )


In [15]:
run_calc(cr)

True

### Extract the results
---

The following code is a simple state machine extracting data from the output file.
The code is an ad-hoc type but can be adapted to extracting other data.

In [ ]:
cr.calc.directory

In [18]:
with open(f'{cr.calc.directory}/abinit.abo') as of:
    st = 0
    for l in of:
        if st==0 and 'Phonon wavevector' in l :
            st=1
            print(f'\nk-point: {[float(v) for v in l.split()[-3:]]}')

        if 0<st:
            #print('>>>', l.strip())
            pass
            
        tok = [] 
        if st > 0:
            tok = l[1:].split()

        if st==2 and len(tok)==6:
            dt.append(float(l.split()[4]))
            if len(dt)==9:
                dt=array(dt).reshape((3,3))
                print('\nDielectric tensor:\n', dt)
                st=0
            
        if st==0 and 'Dielectric tensor' in l:
            dt=[]
            st=2
            continue

            
        if st==31 and len(tok)==6:
            ec.append(float(l.split()[4]))
            if len(ec)==18:
                ec=array(ec).reshape((-1,3))
                print(ec)
                st=0                  

        if st==3 and '(from':
            print(f'\nEffective charges {l.strip()}:')
            st=31
            continue
            
        if st==0 and 'Effective charges' in l:
            st=3
            ec=[]
            continue
            
            
        if st==11 :
            if tok:
                frqs += [float(v) for v in tok]
            else :
                print('Frequencies (cm^-1):\n', frqs)
                st=1
            
        if st==1 :
            if 'cm-1' in l:
                st=11
                frqs = []
            if 'direction' in tok[:1]:
                print(f'\nDirection: {[float(v) for v in l.split()[-3:]]}')
        
        if st==1 and '== DATASET' in l:
            print()
            st=0




Dielectric tensor:
 [[ 9.75441052  0.          0.        ]
 [-0.          9.75441052 -0.        ]
 [-0.         -0.          9.75441052]]

Effective charges (from electric field response):
[[13.27726459  0.         -0.        ]
 [ 2.2279416  -0.          0.        ]
 [ 7.75708322  5.52018137 -7.75708322]
 [ 0.05350041  2.1744412  -0.05350041]
 [ 7.75708322 -7.75708322  5.52018137]
 [ 0.05350041 -0.05350041  2.1744412 ]]

Effective charges (from phonon response):
[[13.27720027  7.75708322  7.75708322]
 [ 0.          5.52011705 -7.75708322]
 [-0.         -7.75708322  5.52011705]
 [ 2.22800672  0.05350041  0.05350041]
 [-0.          2.17450631 -0.05350041]
 [ 0.         -0.05350041  2.17450631]]

k-point: [0.0, 0.0, 0.0]
Frequencies (cm^-1):
 [31.54545, 31.54545, 31.54545, 361.4994, 361.4994, 361.4994]

Direction: [1.0, 0.0, 0.0]
Frequencies (cm^-1):
 [31.54545, 31.54545, 339.4295, 361.4994, 361.4994, 552.8918]

Direction: [0.0, 1.0, 0.0]
Frequencies (cm^-1):
 [31.54545, 31.54545, 303.17